chore: add inclusive terms plugin
bloomberg/coffeechat pull request #6
Opened 2021-05-16 19:49 UTC by Abhilasha3112

**Describe your changes**

- This pr adds eslint plugin for reporting non-inclusive terms in the codebase and suggests alternatives.

- Uses https://github.com/muenzpraeger/eslint-plugin-inclusive-language

- Also, adds stylelint and eslint check within `npm test`

**Testing performed**
Tested by running `npm test` several times.

**Additional context**
Developers can add more non-inclusive terms to the list in `.eslintrc.yml` file.

2021-05-17 09:40 UTC, portenez requested changes
Some actions to take:

- Regenerate the lock file with npm v7 (lockfile to v2)
- Populate the list of terms
- and an optional in there (up2u)

2021-05-17 09:40 UTC, portenez commented on .eslintrc.yml
> +    - error
Can we start with a populated list? There are terms that we definitely should reject from the beginning. I can think of:

- master
- slave
- dummy

We probably should have a list.

2021-05-17 09:40 UTC, portenez commented on package-lock.json
> +  "lockfileVersion": 1,
Can you re-generate with `npm v7` ? either using nvm or a docker container?

2021-05-17 09:40 UTC, portenez commented on package.json
> +    "test": "npm run eslint && npm run stylelint && jest",
[optional] we probably can leave all of these as separate scripts. We'll set up CI using GitHub actions, and we can have different checks per tool. 
We could also leave them here until we actually setup Github actions.

2021-05-28 13:57 UTC, Abhilasha3112 commented on .eslintrc.yml
> +    - error
the above terms are already included by default in the plugin https://github.com/muenzpraeger/eslint-plugin-inclusive-language/blob/primary/lib/config/inclusive-words.json . Hence we do not have to include them separately.

2021-05-28 15:15 UTC, portenez submitted a review, later dismissed

2021-05-28 20:46 UTC, closed without merging